### ISSUE TITLE
How will we add articles?

### ISSUE THREAD

**Issue by amazinigmech2418** [waffleprogramming/Mediwikiwaffle#1]

**Comment by vutondesign** [comment]
@amazinigmech2418 So, I'm not too sure why @redmangospros has made this as we can't host a PHP wiki on Github pages. It has to be hosted locally, for example, on a raspberry pi. This is something we I can look into doing after we finish the main site.

**Comment by amazinigmech2418** [comment]
OK.

**Comment by vutondesign** [comment]
I'm just going to delete this repo for now, as it doesn't serve a purpose.

**Comment by amazinigmech2418** [comment]
OK.
